version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis-ec2
    ports:
      - "6379:6379"

  order-service:
    image: order-service:${IMAGE_TAG}
    container_name: order-ec2
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env.ec2
    volumes:
      - ./logs:${LOGGING_FILE_PATH}
    depends_on:
      - redis
