--
-- PostgreSQL database dump (SAFE / IDEMPOTENT)
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS public.orders (
    id bigint NOT NULL,
    amount double precision,
    customer_name character varying(255),
    s3_file_url character varying(255)
);

ALTER TABLE public.orders OWNER TO postgres;

--
-- Ensure IDENTITY (auto-increment) exists
--
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name='orders'
          AND column_name='id'
          AND is_identity = 'YES'
    ) THEN
        ALTER TABLE public.orders
        ALTER COLUMN id
        ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

--
-- Data for Name: orders; Type: TABLE DATA
--

COPY public.orders (id, amount, customer_name, s3_file_url) FROM stdin;
1	2500	Taher	https://taher-demo-s3-v5.s3.amazonaws.com/orders/acabd48c-50bc-457a-9c6d-17ff1e9872f0-invoice.pdf
\.

--
-- Primary Key (safe)
--
ALTER TABLE public.orders
    DROP CONSTRAINT IF EXISTS orders_pkey;

ALTER TABLE public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

--
-- Fix sequence value (safe)
--
SELECT pg_catalog.setval(
    pg_get_serial_sequence('public.orders', 'id'),
    (SELECT COALESCE(MAX(id), 1) FROM public.orders),
    true
);

--
-- Dump complete
--
