server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
     exposure:
      include: metrics,health

logging:
  level:
    org.springframework.data.redis: DEBUG
    com.order.redis.service.RedisService: INFO
